#:import show_unit_config_dialog factory_flexibility_model.ui.dialogs.dialog_unit_definition.show_unit_config_dialog
#:import show_converter_ratio_dialog factory_flexibility_model.ui.dialogs.dialog_converter_ratios.show_converter_ratio_dialog
#:import show_parameter_config_dialog factory_flexibility_model.ui.dialogs.dialog_parameter_config.show_parameter_config_dialog


Screen:
    MDNavigationLayout:
        ScreenManager:
            Screen:
                MDNavigationRail:
                BoxLayout:
                    orientation: "vertical"
# MAIN MENU BAR ########################################################################################################
                    MDTopAppBar:
                        orientation: "horizontal"
                        title: "Factory Model"
                        id: main_menu_bar
                        left_action_items: [["menu", lambda x: main_menu.set_state("open")]]
                        elevation: 0

                        MDLabel:
                            id: label_session_name
                            font_style: "Subtitle2"
                            theme_text_color: "Custom"
                            text_color: "white"
                            size_hint_y: None
                            height: dp(50)
                            halign: "right"
                            valign: "center"

## BOTTOM NAVIGATION BAR ###############################################################################################
                    MDBottomNavigation:
### TAB: SYSTEM LAYOUT #################################################################################################
                        MDBottomNavigationItem:
                            name: "tab_layout"
                            text: "System Layout"
                            icon: "factory"
                            BoxLayout:
                                orientation: "horizontal"
                                padding: 20

#### LEFT SIDE #########################################################################################################
                                BoxLayout:
                                    orientation: "vertical"
                                    padding: 10
                                    spacing: 10
##### LAYOUT VISUALIZATION #############################################################################################

                                    MDBoxLayout:
                                        orientaion: "horizontal"
                                        # buttons on layout area
                                        MDBoxLayout:
                                            size_hint_x: None
                                            orientation: "vertical"
                                            width: dp(80)
                                            padding: dp(10)

                                            Widget:
                                            MDIconButton:
                                                anchor_y: "center"
                                                icon: "Assets\\add.png"
                                                icon_size: sp(60)
                                                on_release: app.show_component_creation_menu()
                                            Widget:
                                            MDIconButton:
                                                anchor_y: "bottom"
                                                icon: "Assets\\delete.png"
                                                icon_size: sp(60)
                                                id: icon_delete_component
                                                on_release: app.show_component_deletion_dialog()

                                        MDBoxLayout:
                                            id: layout_area
                                            CanvasWidget:
                                                id: canvas_layout
                                                size_hint_x: .8

                                        MDBoxLayout:
                                            size_hint_x: None
                                            width: dp(80)
                                            padding: dp(10)
                                            orientation: "vertical"

                                            MDIconButton:
                                                icon: "magnify-plus"
                                                on_release: app.increase_scaling_factor()
                                                icon_size: sp(30)
                                            MDIconButton:
                                                icon: "magnify-minus"
                                                on_release: app.decrease_scaling_factor()
                                                icon_size: sp(30)
                                            Widget:

##### ASSET CONFIG CARD ################################################################################################
                                        MDCard:
                                            size_hint_x: .3
                                            elevation: 2
                                            ScreenManager:
                                                id: asset_config_screens

        # WELCOME SCREEN ###############################################################################################
                                                Screen:
                                                    name: "welcome_screen"
                                                    BoxLayout:
                                                        orientation: "vertical"
                                                        padding: (20, 20)
                                                        MDLabel:
                                                            text: "Flowtypes"
                                                            font_style: "H5"
                                                            size_hint_y: None
                                                            height:  dp(40)
                                                        ScrollView:
                                                            MDList:
                                                                id: list_flowtypes
                                                        MDRectangleFlatIconButton:
                                                            text: "Unit Definitions"
                                                            icon: "cog"
                                                            line_color: 1, 1, 1, 1
                                                            on_release: show_unit_config_dialog(app)
                                                            pos_hint: {"center_x": .5, "center_y": .5}

        # SOURCE CONFIG SCREEN #########################################################################################
                                                Screen:
                                                    name: "source_config"

                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
                                                        spacing: dp(20)

                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                id: label_source_name
                                                                font_style: "H5"
                                                                size_hint_y: None
                                                                height: dp(50)

                                                            Image:
                                                                id: image_source_configuration
                                                                size_hint: (None, None)
                                                                height: dp(50)
                                                                width: dp(70)
                                                                on_touch_down:  if self.collide_point(*args[1].pos): app.show_icon_selection_dropdown(self)
                                                        MDLabel:
                                                            text: "General"
                                                            font_style: "H6"
                                                            size_hint_y: None
                                                            height: dp(30)
                                                        MDTextField:
                                                            id: textfield_source_name
                                                            hint_text: "Name of the source"
                                                            on_text: app.set_unsaved_changes_on_asset(True)
                                                        MDTextField:
                                                            id: textfield_source_description
                                                            hint_text: "Description of the source"
                                                            on_text: app.set_unsaved_changes_on_asset(True)
                                                        MDTextField:
                                                            id: textfield_source_flowtype
                                                            hint_text: 'Delivered Flow'
                                                            icon_right: "arrow-down-drop-circle-outline"
                                                            on_focus: if self.focus: app.show_flowtype_selection_dropdown(self)
                                                        MDLabel:
                                                            text: "Operating Constraints"
                                                            font_style: "H6"
                                                            size_hint_y: None
                                                            height: dp(30)

                                                        ScrollView:
                                                            do_scroll_y: True
                                                            do_scroll_x: False
                                                            scroll_type:['bars', 'content']
                                                            GridLayout:
                                                                cols: 1
                                                                size_hint_y: None
                                                                size_hint_x: .8
                                                                height: dp(900)
                                                                spacing: dp(10)

                                                                ParameterConfigItem:
                                                                    id: config_source_power_max
                                                                    text: "Maximum Output"
                                                                    parameter: "power_max"
                                                                    value_description: "Maximum Output Flowrate"
                                                                    secondary_text: "10kW"
                                                                    tertiary_text: "Static Value"
                                                                    on_release: show_parameter_config_dialog(app, self)
                                                                    IconLeftWidgetWithoutTouch:
                                                                        icon: "numeric"
                                                                ParameterConfigItem:
                                                                    id: config_source_power_min
                                                                    text: "Minimum Output"
                                                                    secondary_text: "0-10kW"
                                                                    tertiary_text: "Timeseries"
                                                                    IconLeftWidgetWithoutTouch:
                                                                        icon: "chart-line"
                                                                ParameterConfigItem:
                                                                    id: config_source_determined_power
                                                                    text: "Fixed Output"
                                                                    secondary_text: "0-10kW"
                                                                    tertiary_text: "Timeseries"
                                                                    IconLeftWidgetWithoutTouch:
                                                                        icon: "chart-line"
                                                                ParameterConfigItem:
                                                                    id: config_source_availability
                                                                    text: "Availability"
                                                                    secondary_text: "0-10kW"
                                                                    tertiary_text: "Timeseries"
                                                                    IconLeftWidgetWithoutTouch:
                                                                        icon: "chart-line"
                                                                ParameterConfigItem:
                                                                    id: config_source_capacity_charge
                                                                    text: "Capacity Charge"
                                                                    secondary_text: "0-10kW"
                                                                    tertiary_text: "Timeseries"
                                                                    IconLeftWidgetWithoutTouch:
                                                                        icon: "chart-line"
                                                                ParameterConfigItem:
                                                                    id: config_source_co2_emission_per_unit
                                                                    text: "Emissions"
                                                                    secondary_text: "0-10kW"
                                                                    tertiary_text: "Timeseries"
                                                                    IconLeftWidgetWithoutTouch:
                                                                        icon: "chart-line"
                                                                ParameterConfigItem:
                                                                    id: config_source_cost
                                                                    text: "Cost"
                                                                    secondary_text: "0-10kW"
                                                                    tertiary_text: "Timeseries"
                                                                    IconLeftWidgetWithoutTouch:
                                                                        icon: "chart-line"

                                                                ValidatedTextField:
                                                                    id: textfield_source_power_max
                                                                    hint_text: 'Maximum Output Power'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "source"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_source_power_min
                                                                    hint_text: 'Minimum Output Power'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "source"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_source_determined_power
                                                                    hint_text: 'Fixed Operation Level'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "source"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_source_availability
                                                                    hint_text: 'Availability [%]'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "source"
                                                                    on_text: app.validate_textfield_input(self)

                                                                MDLabel:
                                                                    text: "Price of utilization"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                ValidatedTextField:
                                                                    id: textfield_source_capacity_charge
                                                                    hint_text: "Capacity charge [€/unit peak]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "source_capacity_charge"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_source_co2_emission_per_unit
                                                                    hint_text: "CO2 emissions per unit in [kg]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "source_emissions"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_source_cost
                                                                    hint_text: "Cost per unit in [€]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "source_cost"
                                                                    on_text: app.validate_textfield_input(self)

                                                        BoxLayout:
                                                            padding: (10,10)
                                                            size_hint_y: None
                                                            height: dp(50)
                                                            orientation: "horizontal"
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                halign: "right"
                                                                on_release: app.update_config_tab()

                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_source()
                                                                valign: "top"
        # SINK CONFIG SCREEN ###########################################################################################
                                                Screen:
                                                    name: "sink_config"

                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
                                                        spacing: dp(20)

                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                id: label_sink_name
                                                                font_style: "H5"
                                                                size_hint_y: None
                                                                height: dp(50)

                                                            Image:
                                                                id: image_sink_configuration
                                                                size_hint: (None, None)
                                                                height: dp(50)
                                                                width: dp(70)
                                                                on_touch_down: if self.collide_point(*args[1].pos):  app.show_icon_selection_dropdown(self)

                                                        ScrollView:
                                                            do_scroll_y: True
                                                            do_scroll_x: False
                                                            scroll_type:['bars', 'content']

                                                            GridLayout:
                                                                cols: 1
                                                                size_hint_y: None
                                                                size_hint_x: .8
                                                                height: dp(900)
                                                                spacing: dp(10)

                                                                MDLabel:
                                                                    text: "General"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                MDTextField:
                                                                    id: textfield_sink_name
                                                                    hint_text: "Name"
                                                                    on_text: app.set_unsaved_changes_on_asset(True)
                                                                MDTextField:
                                                                    id: textfield_sink_description
                                                                    hint_text: "Description"
                                                                    on_text: app.set_unsaved_changes_on_asset(True)
                                                                MDTextField:
                                                                    id: textfield_sink_flowtype
                                                                    hint_text: 'Flowtype'
                                                                    icon_right: "arrow-down-drop-circle-outline"
                                                                    on_focus: if self.focus: app.show_flowtype_selection_dropdown(self)
                                                                    on_text: app.set_unsaved_changes_on_asset(True)

                                                                MDLabel:
                                                                    text: "Cost of utilization"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                ValidatedTextField:
                                                                    id: textfield_sink_cost
                                                                    hint_text: "Cost per unit of utilization in [€]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "sink_cost"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_sink_revenue
                                                                    hint_text: "Revenue per unit of utilization in [€]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "sink_refund"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_sink_co2_emission_per_unit
                                                                    hint_text: "Emissions per unit in [kg CO2]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "sink_co2_emission"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_sink_co2_refund_per_unit
                                                                    hint_text: "Emissions avoided per unit in [kg CO2]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "sink_co2_refund"
                                                                    on_text: app.validate_textfield_input(self)

                                                                MDLabel:
                                                                    text: "Operating Constraints"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                ValidatedTextField:
                                                                    id: textfield_sink_power_max
                                                                    hint_text: 'Maximum Input Power'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "sink"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_sink_power_min
                                                                    hint_text: 'Minimum Input Power'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "sink"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_sink_demand
                                                                    hint_text: 'Fixed Demand'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "sink"
                                                                    on_text: app.validate_textfield_input(self)

                                                        BoxLayout:
                                                            padding: (10,10)
                                                            orientation: "horizontal"
                                                            size_hint_y: None
                                                            height: dp(50)
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                on_release: app.update_config_tab()

                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_sink()

        # CONVERTER CONFIG SCREEN ######################################################################################
                                                Screen:
                                                    name: "converter_config"

                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
                                                        spacing: dp(20)

                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                id: label_converter_name
                                                                font_style: "H5"
                                                                size_hint_y: None
                                                                height: dp(50)

                                                            Image:
                                                                id: image_converter_configuration
                                                                size_hint: (None, None)
                                                                height: dp(50)
                                                                width: dp(70)
                                                                on_touch_down: if self.collide_point(*args[1].pos):  app.show_icon_selection_dropdown(self)

                                                        MDLabel:
                                                            text: "General"
                                                            font_style: "H6"
                                                            size_hint_y: None
                                                            height: dp(30)

                                                        MDTextField:
                                                            id: textfield_converter_name
                                                            hint_text: "Name"
                                                            on_text: app.set_unsaved_changes_on_asset(True)
                                                        MDTextField:
                                                            id: textfield_converter_description
                                                            hint_text: "Description"
                                                            on_text: app.set_unsaved_changes_on_asset(True)

                                                        BoxLayout:
                                                            padding: (10,10)
                                                            orientation: "horizontal"
                                                            size_hint_y: None
                                                            height: dp(50)
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                on_release: app.update_config_tab()
                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_converter()

                                                        MDLabel:
                                                            text: "Conversion Ratios"
                                                            font_style: "H6"
                                                            size_hint_y: None
                                                            height: dp(30)
                                                        OneLineIconListItem:
                                                            text: "Show Input/Output Ratios"
                                                            on_release: show_converter_ratio_dialog(app)
                                                            IconLeftWidget:
                                                                icon: "cog"

                                                        MDLabel:
                                                            text: "Operating Constraints"
                                                            font_style: "H6"
                                                            size_hint_y: None
                                                            height: dp(30)
                                                        ScrollView:
                                                            do_scroll_y: True
                                                            do_scroll_x: False
                                                            scroll_type:['bars', 'content']
                                                            GridLayout
                                                                cols: 1
                                                                size_hint_y: None
                                                                size_hint_x: .8
                                                                height: dp(1000)
                                                                spacing: dp(10)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_power_max
                                                                    hint_text: "Maximum Operating Point [Conversions/h]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_power_min
                                                                    hint_text: "Minimum Operating Point [Conversions/h]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_availability
                                                                    hint_text: "Availability [%]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_max_pos_ramp_power
                                                                    hint_text: "Maximum Ramp Up [Conversions/h²]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter_rampup"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_max_neg_ramp_power
                                                                    hint_text: "Maximum Ramp Down [Conversions/h²]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter_rampdown"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_eta_max
                                                                    hint_text: "Maximum Efficiency [%]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_power_nominal
                                                                    hint_text: "Operating Point of Max Efficiency [Conversions/h]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_delta_eta_high
                                                                    hint_text: "Rate of efficiency drop when exceeding nominal operating point"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter_delta_eta_high"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_converter_delta_eta_low
                                                                    hint_text: "Rate of efficiency drop when operating below nominal power"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "converter_delta_eta_low"
                                                                    on_text: app.validate_textfield_input(self)


        # THERMALSYSTEM CONFIG SCREEN ##################################################################################
                                                Screen:
                                                    name: "thermalsystem_config"

                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                size_hint_y: None
                                                                id: label_thermalsystem_name
                                                                font_style: "H5"
                                                                height: dp(50)

                                                            Image:
                                                                id: image_thermalsystem_configuration
                                                                size_hint: (None, None)
                                                                height: dp(50)
                                                                width: dp(75)
                                                                on_touch_down: if self.collide_point(*args[1].pos):  app.show_icon_selection_dropdown(self)

                                                        ScrollView:
                                                            do_scroll_y: True
                                                            do_scroll_x: False
                                                            scroll_type:['bars', 'content']

                                                            GridLayout
                                                                cols: 1
                                                                size_hint_y: None
                                                                height: dp(900)
                                                                spacing: dp(10)

                                                                MDLabel:
                                                                    text: "General"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(70)

                                                                MDBoxLayout:
                                                                    orientation: "vertical"
                                                                    padding: 10, 0, 0, 10
                                                                    spacing: dp(10)
                                                                    size_hint_y: None
                                                                    height: dp(200)
                                                                    MDTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_thermalsystem_name
                                                                        hint_text: "Name"
                                                                        on_text: app.set_unsaved_changes_on_asset(True)
                                                                    MDTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_thermalsystem_description
                                                                        hint_text: "Description"
                                                                        on_text: app.set_unsaved_changes_on_asset(True)
                                                                    MDTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_thermalsystem_flowtype
                                                                        hint_text: 'Flow'
                                                                        icon_right: "arrow-down-drop-circle-outline"
                                                                        on_focus: if self.focus: app.show_flowtype_selection_dropdown(self)
                                                                        on_text: app.set_unsaved_changes_on_asset(True)

                                                                MDLabel:
                                                                    text: "Operating Constraints"
                                                                    height: dp(30)
                                                                    font_style: "H6"
                                                                    size_hint_y: None

                                                                MDBoxLayout:
                                                                    orientation: "vertical"
                                                                    spacing: dp(10)
                                                                    padding: 10, 0, 0, 0

                                                                    ValidatedTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_thermalsystem_temperature_start
                                                                        hint_text: "Start temperature"
                                                                        helper_text: "Eingaben plausibel"
                                                                        helper_text_mode: "on_error"
                                                                        validation_type: "thermalsystem_temperature"
                                                                        on_text: app.validate_textfield_input(self)
                                                                MDBoxLayout:
                                                                    orientation: "horizontal"
                                                                    size_hint_y: None
                                                                    padding: 10, 0, 0, 0
                                                                    height: dp(60)

                                                                    ValidatedTextField:
                                                                        id: textfield_thermalsystem_temperature_ambient
                                                                        hint_text: "ambient temperature"
                                                                        helper_text: "Eingaben plausibel"
                                                                        helper_text_mode: "on_error"
                                                                        validation_type: "thermalsystem_temperature"
                                                                        #hint_text_color_focus: "green"
                                                                        #line_color_focus: "green"
                                                                        #pos_hint:{"center_x": .5, "center_y": .5}
                                                                        #size_hint_x: .5
                                                                        on_text: app.validate_textfield_input(self)
                                                                        #on_text: app.validate_thermalsystem(self)
                                                                        #on_text_validate: app.on_text_validate(textfield_thermalsystem_temperature_ambient)
                                                                        size_hint_x: .7
                                                                    MDCheckbox:
                                                                        id: switch_thermalsystem_temperature_ambient
                                                                        on_active: app.set_unsaved_changes_on_asset(True)
                                                                        size_hint_x: .1
                                                                    MDIcon:
                                                                        icon: "chart-line"
                                                                        pos_hint: {"center_x": .5, "center_y": .5}
                                                                        size_hint_x: .2
                                                                    Widget:
                                                                        size_hint_x: .05

                                                                MDBoxLayout:
                                                                    orientation: "horizontal"
                                                                    size_hint_y: None
                                                                    padding: 10, 0, 0, 0
                                                                    height: dp(60)

                                                                    ValidatedTextField:
                                                                        id: textfield_thermalsystem_temperature_max
                                                                        hint_text: "Maximum tempertaure"
                                                                        helper_text: "Eingaben plausibel"
                                                                        helper_text_mode: "on_error"
                                                                        validation_type: "thermalsystem_temperature"
                                                                        on_text: app.validate_textfield_input(self)
                                                                        #on_text: app.validate_thermalsystem(self)
                                                                        size_hint_x: .7
                                                                    MDCheckbox:
                                                                        id: switch_thermalsystem_temperature_max
                                                                        validation_type: "thermalsystem_temperature"
                                                                        on_active: app.on_checkbox_active(*args)
                                                                        size_hint_x: .1
                                                                    MDIcon:
                                                                        icon: "chart-line"
                                                                        pos_hint: {"center_x": .5, "center_y": .5}
                                                                        size_hint_x: .2
                                                                    Widget:
                                                                        size_hint_x: .05

                                                                MDBoxLayout:
                                                                    orientation: "horizontal"
                                                                    size_hint_y: None
                                                                    padding: 10, 0, 0, 0
                                                                    height: dp(60)

                                                                    ValidatedTextField:
                                                                        id: textfield_thermalsystem_temperature_min
                                                                        hint_text: "Minimum temperature"
                                                                        helper_text: "Eingaben plausibel"
                                                                        helper_text_mode: "on_error"
                                                                        validation_type: "thermalsystem_temperature"
                                                                        on_text: app.validate_textfield_input(self)
                                                                        size_hint_x: .7
                                                                    MDCheckbox:
                                                                        id: switch_thermalsystem_temperature_min
                                                                        on_active: app.set_unsaved_changes_on_asset(True)
                                                                        size_hint_x: .1
                                                                    MDIcon:
                                                                        icon: "chart-line"
                                                                        pos_hint: {"center_x": .5, "center_y": .5}
                                                                        size_hint_x: .2
                                                                    Widget:
                                                                        size_hint_x: .05

                                                                MDBoxLayout:
                                                                    orientation: "horizontal"
                                                                    size_hint_y: None
                                                                    height: dp(60)
                                                                    padding: 10, 0, 0, 0

                                                                    ValidatedTextField:
                                                                        size_hint_x: .7
                                                                        id: textfield_thermalsystem_sustainable
                                                                        hint_text: "sustainable"
                                                                        helper_text: "mistake"
                                                                        helper_text_mode: "on_error"
                                                                        validation_type: "thermalsystem_sustainable"
                                                                        on_text: app.validate_textfield_input(self)

                                                                    MDCheckbox:
                                                                        id: sustainable
                                                                        on_active: app.set_unsaved_changes_on_asset(True)
                                                                        size_hint_x: .1
                                                                    Widget:
                                                                        size_hint_x: .11

                                                                MDLabel:
                                                                    text: "Efficiency"
                                                                    height: dp(100)
                                                                    font_style: "H6"
                                                                    size_hint_y: None

                                                                MDBoxLayout:
                                                                    padding: 10, 0, 0, 0
                                                                    orientation: "vertical"
                                                                    spacing: dp(10)
                                                                    size_hint_y: None
                                                                    height: dp(100)

                                                                    ValidatedTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_thermalsystem_R
                                                                        helper_text: "mistake"
                                                                        helper_text_mode: "on_error"
                                                                        hint_text: "R"
                                                                        validation_type: "thermalsystem_R"
                                                                        on_text: app.validate_textfield_input(self)

                                                                    ValidatedTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_thermalsystem_C
                                                                        hint_text: "C"
                                                                        helper_text: "mistake"
                                                                        helper_text_mode: "on_error"
                                                                        validation_type: "thermalsystem_C"
                                                                        on_text: app.validate_textfield_input(self)
                                                        BoxLayout:
                                                            padding: (10,10)
                                                            size_hint_y: None
                                                            orientation: "horizontal"
                                                            height:50
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                halign: "right"
                                                                on_release: app.update_config_tab()

                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_thermalsystem()
                                                                valign: "top"

        # SCHEDULE CONFIG SCREEN #######################################################################################
                                                Screen:
                                                    name: "schedule_config"
                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
        # SCHEDULE: Position of header with image in screen ############################################################
                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                size_hint_y: None
                                                                id: label_schedule_name
                                                                font_style: "H5"
                                                                height: dp(50)

                                                            Image:
                                                                id: image_schedule_configuration
                                                                size_hint: (None, None)
                                                                height: dp(50)
                                                                width: dp(75)
                                                                on_touch_down: if self.collide_point(*args[1].pos):  app.show_icon_selection_dropdown(self)

                                                        ScrollView:
                                                            do_scroll_y: True
                                                            do_scroll_x: False
                                                            scroll_type:['bars', 'content']

                                                            GridLayout
                                                                cols: 1
                                                                size_hint_y: None
                                                                height: dp(1000)
                                                                spacing: dp(10)

        # SCHEDULE: Position of boxlayout with textfields ##############################################################
                                                                MDLabel:
                                                                    text: "General"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(70)

                                                                MDBoxLayout:
                                                                    orientation: "vertical"
                                                                    padding: 10, 0, 0, 0
                                                                    spacing: dp(10)
                                                                    size_hint_y: None
                                                                    height: dp(100)
                                                                    MDTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_schedule_name
                                                                        hint_text: "Name"
                                                                        on_text: app.set_unsaved_changes_on_asset(True)
                                                                    MDTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_schedule_description
                                                                        hint_text: "Description"
                                                                        on_text: app.set_unsaved_changes_on_asset(True)

                                                                MDLabel:
                                                                    text: "Operating Constraints"
                                                                    height: dp(70)
                                                                    font_style: "H6"
                                                                    size_hint_y: None

                                                                MDBoxLayout:
                                                                    padding: 10, 0, 0, 0
                                                                    orientation: "vertical"
                                                                    size_hint_y: None
                                                                    height: dp(50)
                                                                    ValidatedTextField:
                                                                        size_hint_x: .75
                                                                        id: textfield_schedule_power_max
                                                                        hint_text: "Maximum power flow"
                                                                        helper_text: "mistake"
                                                                        helper_text_mode: "on_error"
                                                                        validation_type: "schedule_power_max"
                                                                        on_text: app.validate_textfield_input(self)
                                                        BoxLayout:
                                                            padding: (10,10)
                                                            size_hint_y: None
                                                            orientation: "horizontal"
                                                            height:50
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                halign: "right"
                                                                on_release: app.update_config_tab()

                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_schedule()
                                                                valign: "top"

        # DEADTIME CONFIG SCREEN #######################################################################################
                                                Screen:
                                                    name: "deadtime_config"

                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
                                                        spacing: dp(20)

                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                size_hint_y: None
                                                                id: label_deadtime_name
                                                                font_style: "H5"
                                                                size_hint_y: None
                                                                height: dp(50)

                                                            Image:
                                                                id: image_deadtime_configuration
                                                                size_hint: (None, None)
                                                                height: dp(50)
                                                                width: dp(75)
                                                                on_touch_down: if self.collide_point(*args[1].pos):  app.show_icon_selection_dropdown(self)
                                                        ScrollView:
                                                            do_scroll_y: True
                                                            do_scroll_x: False
                                                            scroll_type:['bars', 'content']
                                                            GridLayout:
                                                                cols: 1
                                                                size_hint_y: None
                                                                size_hint_x: .8
                                                                height: dp(900)
                                                                spacing: dp(10)

                                                                MDLabel:
                                                                    text: "General"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                MDTextField:
                                                                    id: textfield_deadtime_name
                                                                    hint_text: "Name"
                                                                    on_text: app.set_unsaved_changes_on_asset(True)
                                                                MDTextField:
                                                                    id: textfield_deadtime_description
                                                                    hint_text: "Description"
                                                                    on_text: app.set_unsaved_changes_on_asset(True)
                                                                MDTextField:
                                                                    id: textfield_deadtime_flowtype
                                                                    hint_text: 'Flowtype'
                                                                    icon_right: "arrow-down-drop-circle-outline"
                                                                    on_focus: if self.focus: app.show_flowtype_selection_dropdown(self)

                                                                MDLabel:
                                                                    text: "Operating Constraints"
                                                                    height: dp(30)
                                                                    font_style: "H6"
                                                                    size_hint_y: None

                                                                ValidatedTextField:
                                                                    id: textfield_deadtime_delay
                                                                    hint_text: "Delay"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "deadtime_delay"
                                                                    on_text: app.validate_textfield_input(self)

                                                        BoxLayout:
                                                            padding: (10,10)
                                                            size_hint_y: None
                                                            orientation: "horizontal"
                                                            height:50
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                halign: "right"
                                                                on_release: app.update_config_tab()

                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_deadtime()
                                                                valign: "top"


        # STORAGE CONFIG SCREEN ######################################################################################
                                                Screen:
                                                    name: "storage_config"

                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
                                                        spacing: dp(20)

                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                id: label_storage_name
                                                                font_style: "H5"
                                                                size_hint_y: None
                                                                height: dp(50)

                                                            Image:
                                                                id: image_storage_configuration
                                                                size_hint: (None, None)
                                                                height: dp(50)
                                                                width: dp(70)
                                                                on_touch_down:  if self.collide_point(*args[1].pos): app.show_icon_selection_dropdown(self)

                                                        ScrollView:
                                                            do_scroll_y: True
                                                            do_scroll_x: False
                                                            scroll_type:['bars', 'content']

                                                            GridLayout:
                                                                cols: 1
                                                                size_hint_y: None
                                                                size_hint_x: .8
                                                                height: dp(1000)
                                                                spacing: dp(10)

                                                                MDLabel:
                                                                    text: "General"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                MDTextField:
                                                                    id: textfield_storage_name
                                                                    hint_text: "Name of the storage"
                                                                    on_text: app.set_unsaved_changes_on_asset(True)
                                                                MDTextField:
                                                                    id: textfield_storage_description
                                                                    hint_text: "Description of the storage"
                                                                    on_text: app.set_unsaved_changes_on_asset(True)
                                                                MDTextField:
                                                                    id: textfield_storage_flowtype
                                                                    hint_text: 'Flowtype'
                                                                    icon_right: "arrow-down-drop-circle-outline"
                                                                    on_focus: app.show_flowtype_selection_dropdown(self)
                                                                    on_text: app.set_unsaved_changes_on_asset(True)

                                                                MDLabel:
                                                                    text: "Operating Constraints"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                ValidatedTextField:
                                                                    id: textfield_storage_capacity
                                                                    hint_text: 'Capacity'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "storage_capacity"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_storage_power_max_charge
                                                                    hint_text: 'Maximum Charging Power'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "storage_power_max"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_storage_power_max_discharge
                                                                    hint_text: 'Maximum Discharging Power'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "storage_power_min"
                                                                    on_text: app.validate_textfield_input(self)

                                                                ValidatedTextField:
                                                                    id: textfield_storage_soc_start
                                                                    hint_text: 'SOC Start [%]'
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "storage_soc_start"
                                                                    on_text: app.validate_textfield_input(self)

                                                                MDLabel:
                                                                    text: "Efficiency"
                                                                    font_style: "H6"
                                                                    size_hint_y: None
                                                                    height: dp(30)

                                                                ValidatedTextField:
                                                                    id: textfield_storage_efficiency
                                                                    hint_text: "Base Efficiency [%]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "storage_efficiency"
                                                                    on_text: app.validate_textfield_input(self)
                                                                ValidatedTextField:
                                                                    id: textfield_storage_leakage_time
                                                                    hint_text: "Absolute Leakage"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "storage_leakage_time"
                                                                    on_text: app.validate_textfield_input(self)
                                                                ValidatedTextField:
                                                                    id: textfield_storage_leakage_soc
                                                                    hint_text: "SOC Based Leakage [%/h]"
                                                                    helper_text: "mistake"
                                                                    helper_text_mode: "on_error"
                                                                    validation_type: "storage_leakage_soc"
                                                                    on_text: app.validate_textfield_input(self)

                                                        BoxLayout:
                                                            padding: (10,10)
                                                            size_hint_y: None
                                                            orientation: "horizontal"
                                                            height: dp(50)
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                on_release: app.update_config_tab()

                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_storage()
        # POOL CONFIG SCREEN ###########################################################################################
                                                Screen:
                                                    name: "pool_config"

                                                    MDBoxLayout:
                                                        orientation: "vertical"
                                                        padding: dp(20)
                                                        spacing: dp(20)

                                                        MDBoxLayout:
                                                            size_hint_y: None
                                                            height: dp(70)
                                                            orientation: "horizontal"

                                                            MDLabel:
                                                                id: label_pool_name
                                                                font_style: "H5"
                                                                size_hint_y: None
                                                                height: dp(50)
                                                            Image:
                                                                size_hint: (None, None)
                                                                height: dp(70)
                                                                width: dp(70)
                                                                source: "Assets\\defaults\\pool.png"

                                                        MDLabel:
                                                            text: "General"
                                                            font_style: "H6"
                                                            size_hint_y: None
                                                            height: dp(30)

                                                        MDTextField:
                                                            id: textfield_pool_name
                                                            hint_text: 'Name'
                                                            on_text: app.set_unsaved_changes_on_asset(True)
                                                        MDTextField:
                                                            id: textfield_pool_description
                                                            hint_text: 'Description'
                                                            on_text: app.set_unsaved_changes_on_asset(True)
                                                        MDTextField:
                                                            id: textfield_pool_flowtype
                                                            hint_text: 'Flow'
                                                            icon_right: "arrow-down-drop-circle-outline"
                                                            on_focus: if self.focus: app.show_flowtype_selection_dropdown(self)

                                                        Widget:
                                                        BoxLayout:
                                                            padding: (10,10)
                                                            size_hint_y: None
                                                            orientation: "horizontal"
                                                            height: dp(50)
                                                            Widget:
                                                            MDFlatButton:
                                                                text: "Revert Changes"
                                                                on_release: app.update_config_tab()

                                                            MDRaisedButton:
                                                                text: "Save Changes"
                                                                on_release: app.save_changes_on_pool()
### TAB TIMESERIS  ######################################################################################################
                        MDBottomNavigationItem:
                            name: "tab_timeseries"
                            text: "Timeseries"
                            icon: "database-import"

                            ScreenManager:
                                Screen:
                                    id: timeseries_screens

### TAB SIMULATION  ######################################################################################################
                        MDBottomNavigationItem:
                            name: "tab_simulation"
                            text: "Simulation"
                            icon: "database-import"

                            ScreenManager:
                                id: simulation_screens

## COMPONENT CREATION MENU ######################################################################################################
                MDNavigationDrawer:
                    id: component_shelf
                    opening_time: 0
                    closing_time: 0
                    enable_swiping: False
                    elevation: 1
                    BoxLayout:
                        orientation: "vertical"
                        MDLabel:
                            text: "Add Component"
                            size_hint_y: .05
                            #height: dp(30)
                            font_style: 'H5'
                            halign: "center"
                        CanvasWidget:
                            id: canvas_shelf
                            size_hint_y: .6
                        Image:
                            source: "Assets\\swipe_instruction.png"
                            size_hint_y: .05
                            #height: dp(80)
                            pos_hint:{"center_x": .5, "center_y": .5}
                        MDLabel:
                            text: "Drag assets on layout to add"
                            size_hint_y: .02
                            font_style: 'Caption'
                            #height: dp(30)
                            halign: "center"

## LEFT MAIN MENU ######################################################################################################
                MDNavigationDrawer:
                    id: main_menu

# ADDITIONAL LAYOUTS ###################################################################################################
<DragLabel>:
    # Define the properties for the DragLabel
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 10000000
    drag_distance: 0

#       TIMESERIES SELECTION DIALOG ####################################################################################
<dialog_timeseries_selection>
    orientation: "vertical"
    size_hint: (None, None)
    #adaptive_size: True
    height: dp(600)
    width: dp(500)

    MDBoxLayout:
        size_hint_y: None
        height: dp(60)
        orientation: "horizontal"
        MDTextField:
            id: search_field_timeseries
            hint_text: 'Search Timeseries'
            on_text: app.update_timeseries_list()

        MDIconButton:
            size_hint: (None, None)
            icon: "import"
            on_release: app.import_timeseries()

    ScrollView:
        MDList:
            id: list_timeseries

    MDRaisedButton:
        text: "USE"
        halign: "right"
        on_release: app.close_dialog()

#       FLOWTYPE DEFINITION DIALOG ####################################################################################
<dialog_flowtype_definition>
    size_hint: None, None
    width:dp(800)
    height:dp(700)
    orientation: "vertical"
    MDBoxLayout:
        orientation: "horizontal"
        size_hint_y: None
        height: dp(30)
        MDLabel:
            id: label_flowtype_name
            font_style: 'H5'
        MDIconButton:
            id: button_flowtype_delete
            icon: "delete"
            halign: "right"
    MDLabel:
        text: "Name"
        size_hint_y: None
        height: dp(30)
    MDTextField:
        id: textfield_flowtype_name
        hint_text: 'Specify a name for the flowtype'
        size_hint_y: None
        mode: "rectangle"
        height: dp(30)
        helper_text_mode: "on_error"
        helper_text: "Name is already assigned within the factory"
        on_text: button_flowtype_save.disabled = False
    MDLabel:
        text: "Description"
        size_hint_y: None
        height: dp(30)
    MDTextField:
        id: textfield_flowtype_description
        hint_text: 'Description of the flowtype'
        size_hint_y: None
        mode: "rectangle"
        height: dp(30)
        on_text: button_flowtype_save.disabled = False
    MDBoxLayout:
        orientation: "horizontal"
        MDBoxLayout:
            orientation: "vertical"
            MDLabel:
                text: "Unit"
                size_hint_y: None
                height: dp(30)
            MDDropDownItem:
                id: textfield_flowtype_unit
                text: "No Unit selected"
                size_hint_y: None
                height: dp(30)
                hint_text: 'Represented by unit:'
                on_release: app.show_unit_selection_dropdown(self)
                on_release: button_flowtype_save.disabled = False
            MDBoxLayout:
                orientation: "horizontal"
                MDCheckbox:
                    id: checkbox_flowtype_losses
                    size_hint: None, None
                    height: dp(30)
                    width: dp(30)
                    on_active: button_flowtype_save.disabled = False
                MDLabel:
                    size_hint_y: None
                    height: dp(30)
                    text: "Flowtype represents losses"
            Widget:
        MDBoxLayout:
            orientation: "vertical"
            MDLabel:
                text: "Color"
                size_hint_y: None
                height: dp(30)
            MDIconButton:
                id: icon_flowtype_color
                icon: "palette"
                icon_size: "100sp"
                theme_icon_color: "Custom"
                icon_color: "#1D4276"
                on_release: app.show_color_picker()
            Widget:
    Widget:
    MDBoxLayout:
        orientation: "horizontal"
        MDRaisedButton:
            id: button_flowtype_save
            text: "Save changes"
            on_release: app.save_changes_on_flowtype()
            on_release: app.close_dialog()
            disabled: True
        MDRaisedButton:
            text: "Cancel"
            on_release: app.close_dialog()
